[package]
name = "range_management_card_swipe"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.1"
chrono = "0.4.19"
redis = "0.21.4"
